import { Month } from './types';

export const roadmapData: Month[] = [
  {
    month: 1,
    title: "The Foundation: Core Go & Software Engineering Mindset",
    focus: "Mastering Go idioms, concurrency, memory management, and rigorous testing.",
    capstoneProject: "CLI-based Concurrent Log Analyzer pulling from local files and simulating streaming data.",
    architectureReview: "Monolithic CLI vs modular packages. Discussing package boundaries and interface segregation.",
    performanceReview: "Benchmarking file reading techniques (bufio vs raw bytes). Profiling memory allocations.",
    productionChecklist: [
      "Use of context.Context for cancellation everywhere.",
      "No bare goroutines (always use waitgroups or errgroup).",
      "Comprehensive test coverage (>80%) with table-driven tests.",
      "Proper error wrapping with custom error types.",
      "GitHub Actions CI pipeline for linting (golangci-lint) and testing."
    ],
    weeks: [
      {
        week: 1,
        theme: "Advanced Syntax, Structs, and Interfaces",
        whyItMatters: "Building maintainable systems requires understanding how Go handles state and boundaries, differing significantly from OOP languages.",
        juniorMistakes: "Trying to write Java/Python in Go. Overusing pointers. Returning interfaces instead of concrete types.",
        midLevelMindset: "Accept interfaces, return structs. Design for composition over inheritance.",
        days: [
          {
            day: 1,
            title: "Go Toolchain and Project Lifecycle",
            goal: "Master Go modules, environments, and basic tooling.",
            technologies: ["Go CLI", "go mod", "golangci-lint"],
            concepts: ["Module proxy", "Vendoring", "Semantic versioning in Go", "GOPATH vs Modules"],
            codingTasks: "Set up a new project template with Makefile, linting, and a generic internal package structure.",
            miniChallenges: "Force a module downgrade and resolve the dependency conflict.",
            realWorldScenarios: "A junior team member broke the build by pulling a breaking package version. You must isolate and fix it.",
            deliverables: "A repository with CI running golangci-lint on PRs.",
            githubExpectations: "Initial commit with structured modular layout and CI YAML, following Conventional Commits.",
            documentationTasks: "Write a complete README.md explaining how to bootstrap the environment.",
            testingRequirements: "Write a dummy test to ensure CI passes."
          },
          {
            day: 2,
            title: "Memory, Pointers, and Escape Analysis",
            goal: "Understand exactly where Go allocates memory and why.",
            technologies: ["Go compiler", "go build -gcflags"],
            concepts: ["Stack vs Heap", "Escape Analysis", "Value vs Pointer semantics"],
            codingTasks: "Write functions passing large structs by value vs pointer. Analyze allocations.",
            miniChallenges: "Refactor a memory-heavy function to zero allocations using `sync.Pool`.",
            realWorldScenarios: "Your microservice is OOM-killing in production due to massive GC pauses. You must identify what is escaping to the heap.",
            deliverables: "A markdown report of `go build -gcflags=\"-m\"` outputs comparing approaches.",
            githubExpectations: "Feature branch with memory optimizations and benchmark tests.",
            documentationTasks: "Document when the team should use pointers vs values.",
            testingRequirements: "Write Go benchmarks (BenchmarkXxx) proving optimization."
          },
          {
            day: 3,
            title: "Interface Design & Dependency Injection",
            goal: "Decouple systems using small, explicit interfaces.",
            technologies: ["Go interfaces", "Wire (optional)"],
            concepts: ["Implicit satisfaction", "Interface segregation", "Mocking via interfaces"],
            codingTasks: "Refactor a hardcoded database connection into a `Store` interface. Implement a PostgresStore and a MemoryStore.",
            miniChallenges: "Create an interface composed of `io.Reader` and `io.Closer`.",
            realWorldScenarios: "You need to test a service that calls an external payment API. The API is rate-limited. You must inject a mock.",
            deliverables: "Service layer entirely decoupled from the persistence layer.",
            githubExpectations: "PR titled 'Refactor: Decouple storage using Store interface' with clear review notes.",
            documentationTasks: "Update architectural diagram showing dependency inversion.",
            testingRequirements: "Inject MemoryStore in unit tests to achieve 100% logic coverage."
          },
          {
            day: 4,
            title: "Error Handling & Wrapping",
            goal: "Implement robust, traceable error chains.",
            technologies: ["errors package", "fmt.Errorf"],
            concepts: ["Sentinel errors", "Error wrapping (%w)", "Is() and As()", "Custom error structs"],
            codingTasks: "Create a custom APIError struct tracking HTTP code, message, and internal trace. Implement custom `.Error()`. ",
            miniChallenges: "Write a middleware that intercepts custom errors and logs the trace while returning a masked message to the user.",
            realWorldScenarios: "Users report '500 Internal Error' but logs show 'connection refused'. You need context on *which* subsystem failed.",
            deliverables: "A centralized error package used across the project.",
            githubExpectations: "Commits showing migration from `errors.New` to contextual wrapped errors.",
            documentationTasks: "Write an RFC on the team's new error handling standard.",
            testingRequirements: "Test error equality using `errors.Is` and extraction using `errors.As`."
          },
          {
            day: 5,
            title: "Reflection & Generics Basics",
            goal: "Understand meta-programming in Go and when (not) to use it.",
            technologies: ["reflect package", "Go 1.18+ Generics"],
            concepts: ["Type parameters", "Constraints", "Reflection performance costs", "Struct tags"],
            codingTasks: "Write a generic `Filter[T any]` function. Write a reflection-based struct-to-map converter.",
            miniChallenges: "Parse custom struct tags (e.g., `validate:\"required\"`) using reflection.",
            realWorldScenarios: "You are building a custom ORM or configuration parser where types are unknown until runtime.",
            deliverables: "A utility package containing the generic helpers and custom tag parser.",
            githubExpectations: "Code review simulation: self-review acknowledging the performance hit of the reflection code.",
            documentationTasks: "Add godoc comments warning about reflection performance.",
            testingRequirements: "Benchmark generic version vs reflection version vs concrete version."
          }
        ]
      },
      {
        week: 2,
        theme: "Concurrency Deep Dive",
        whyItMatters: "Go's superpower is concurrency. Misunderstanding it leads to race conditions, deadlocks, and goroutine leaks in production.",
        juniorMistakes: "Using goroutines for everything. Forgetting to close channels. Ignoring the `-race` detector.",
        midLevelMindset: "Concurrency is not parallelism. Always know how and when a goroutine will terminate.",
        days: [
          {
            day: 1,
            title: "Goroutines & WaitGroups",
            goal: "Safely execute concurrent tasks and sync completion.",
            technologies: ["sync.WaitGroup", "go keyword"],
            concepts: ["Fork-join model", "Goroutine scheduling", "Data races"],
            codingTasks: "Create a bulk image downloader that fetches 100 URLs concurrently and waits for all to finish.",
            miniChallenges: "Intentionally create a data race and use `go run -race` to find it.",
            realWorldScenarios: "A cron job needs to fetch data from 5 different third-party APIs simultaneously to meet SLA.",
            deliverables: "Concurrent fetching script with zero race conditions.",
            githubExpectations: "Commit with CI step explicitly calling `go test -race`.",
            documentationTasks: "Document the maximum concurrent connections expected.",
            testingRequirements: "Unit tests enforcing timeout if WaitGroup fails to release."
          },
          {
            day: 2,
            title: "Channels & Select Statements",
            goal: "Communicate between goroutines elegantly.",
            technologies: ["Channels", "select"],
            concepts: ["Buffered vs Unbuffered", "Blocking semantics", "Deadlocks", "Fan-in/Fan-out basic"],
            codingTasks: "Implement a producer-consumer system where 1 producer sends telemetry data to 3 consumer workers via channels.",
            miniChallenges: "Use `select` to handle a graceful shutdown signal alongside incoming data.",
            realWorldScenarios: "An event stream is producing logs faster than the DB can write them. You must buffer and chunk them.",
            deliverables: "A working worker-pool processing jobs from a channel.",
            githubExpectations: "PR focusing on channel closure safety (who closes the channel?).",
            documentationTasks: "Draw a sequence diagram of the channel flow.",
            testingRequirements: "Write a test simulating channel blocking to ensure no deadlocks."
          },
          {
            day: 3,
            title: "The Context Package",
            goal: "Master cancellation, timeouts, and request scoping.",
            technologies: ["context package"],
            concepts: ["context.WithTimeout", "context.WithCancel", "context.WithValue"],
            codingTasks: "Modify the week's fetcher to halt all pending HTTP requests if one critical request fails, using context cancellation.",
            miniChallenges: "Pass a correlation ID through a context and extract it in a dummy logging function.",
            realWorldScenarios: "A user closes their browser while a heavy DB query is running. You must cancel the query to save resources.",
            deliverables: "Library functions where the first parameter is ALWAYS `ctx context.Context`.",
            githubExpectations: "Refactor commit propagating context through all layers.",
            documentationTasks: "Write guidelines on what data belongs in `context.WithValue` (hint: strictly request-scoped data).",
            testingRequirements: "Test that functions exit immediately when `ctx.Done()` is closed."
          },
          {
            day: 4,
            title: "Advanced Concurrency Patterns",
            goal: "Build standard, reusable concurrency topologies.",
            technologies: ["golang.org/x/sync/errgroup"],
            concepts: ["ErrGroup", "Worker Pools", "Pipelines", "Rate Limiting with Tickers"],
            codingTasks: "Refactor Day 1's WaitGroup implementation to use `errgroup`. Add a global rate limiter allowing only 10 requests/second.",
            miniChallenges: "Implement functional options pattern to configure the Worker Pool size.",
            realWorldScenarios: "Scraping an external API without a rate limiter got your company's IP banned. Implement a robust token bucket.",
            deliverables: "A highly resilient concurrent scraper with rate limiting and error aggregation.",
            githubExpectations: "PR with comparison notes between standard WaitGroup and ErrGroup.",
            documentationTasks: "Comment code blocks explaining the rate-limiting math.",
            testingRequirements: "Table-driven tests simulating different worker numbers and error rates."
          },
          {
            day: 5,
            title: "Mutexes and Atomic Operations",
            goal: "Manage shared state safely avoiding lock contention.",
            technologies: ["sync.Mutex", "sync.RWMutex", "sync/atomic"],
            concepts: ["Lock contention", "Atomic counters", "Cache lines (overview)"],
            codingTasks: "Build an in-memory cache system. First use Mutex, then RWMutex, then atomic map for a simple view counter.",
            miniChallenges: "Create a system deadlock using two mutexes, then fix it by enforcing lock ordering.",
            realWorldScenarios: "Your concurrent cache scales poorly because readers are blocking other readers. Upgrade to RWMutex.",
            deliverables: "A thread-safe `Cache` package.",
            githubExpectations: "Commit history showing the evolution from unsafe map -> Mutex -> RWMutex.",
            documentationTasks: "Document when to use channels vs Mutexes (sharing memory by communicating vs communicating by sharing memory).",
            testingRequirements: "High-concurrency benchmark testing Mutex vs RWMutex speeds."
          }
        ]
      }
    ]
  },
  {
    month: 2,
    title: "Backend Core: APIs, Postgres & Architecture",
    focus: "Building production-grade REST APIs, mastering SQL in Go, and Clean Architecture.",
    capstoneProject: "A fully functional REST API for a DevOps/Platform Configuration Tool with Auth, Postgres, and Docker.",
    architectureReview: "Hexagonal Architecture implementation. Ensuring the domain layer has zero external dependencies.",
    performanceReview: "Database connection pooling tuning. Explaining N+1 query problems and fixing them using joins.",
    productionChecklist: [
      "Graceful HTTP server shutdown.",
      "Database migrations included in deployment.",
      "Structured JSON logging implemented.",
      "Environment variables parsed securely.",
      "CORS properly configured."
    ],
    weeks: [
      {
        week: 1,
        theme: "REST APIs & Middleware",
        whyItMatters: "APIs are the contract between systems. Poorly designed APIs break clients, are insecure, and impossible to scale.",
        juniorMistakes: "Putting business logic in HTTP handlers. Ignoring HTTP status codes. No request validation.",
        midLevelMindset: "Handlers only parse HTTP and call Services. Strict adherence to REST semantics and idempotency.",
        days: [
          {
            day: 1,
            title: "Net/HTTP and Routing",
            goal: "Master the standard library HTTP package and standard multiplexers.",
            technologies: ["net/http", "chi or gorilla/mux"],
            concepts: ["http.HandlerFunc", "ResponseWriter", "REST semantics", "Idempotency"],
            codingTasks: "Build a CRUD API for 'Users' using purely `net/http` and `chi`. Map standard HTTP methods to operations.",
            miniChallenges: "Implement a custom NOT FOUND and METHOD NOT ALLOWED JSON response.",
            realWorldScenarios: "Clients complain your API returns 200 OK even when it fails with an error payload. Fix HTTP codes.",
            deliverables: "A running HTTP server handling basic JSON payloads.",
            githubExpectations: "Setup commit introducing the router and basic handler structure.",
            documentationTasks: "Write an OpenAPI/Swagger basic spec or detailed markdown documentation for the routes.",
            testingRequirements: "Use `httptest` to test the handlers without spinning up a real network port."
          },
           {
            day: 2,
            title: "Middleware Chain & Context",
            goal: "Intercept requests for cross-cutting concerns.",
            technologies: ["Middleware pattern"],
            concepts: ["Context propagation", "Authentication layer", "Logging layers", "Panic recovery"],
            codingTasks: "Write 3 middlewares: RequestLogger, PanicRecoverer, and a BasicAuth protector.",
            miniChallenges: "Inject a TraceID in the first middleware and print it in the handler using Context.",
            realWorldScenarios: "A nil pointer dereference in an obscure handler is crashing the entire server. Implement a recovery middleware.",
            deliverables: "A robust middleware pipeline wrapping all routes.",
            githubExpectations: "PR applying middleware globally and to specific sub-routers.",
            documentationTasks: "Document the order of middleware execution.",
            testingRequirements: "Write tests asserting middleware blocks unauthorized requests with 401."
          },
          {
            day: 3,
             title: "JSON Decoding & Validation",
            goal: "Safely parse and strict-validate external input.",
            technologies: ["encoding/json", "go-playground/validator"],
            concepts: ["Unmarshal vs Decode", "Struct tags", "Unknown fields", "XSS prevention basics"],
            codingTasks: "Implement strict JSON decoding that errors on unknown fields. Add struct validation for emails and passwords.",
            miniChallenges: "Write a custom validator for a complex rule (e.g., password must contain a special character).",
            realWorldScenarios: "Attackers are sending massive JSON payloads attempting to OOM the server. Use `http.MaxBytesReader`.",
            deliverables: "A secure request parsing helper function.",
            githubExpectations: "Implement common custom error responses for validation failures.",
            documentationTasks: "Document the exact JSON schemas required.",
            testingRequirements: "Write fuzz tests or exhaustive table-driven tests for malformed JSON inputs."
          },
           {
            day: 4,
            title: "Clean Architecture Setup",
            goal: "Separate concerns: Handlers -> Services -> Repositories.",
            technologies: ["Domain-Driven Design basics"],
            concepts: ["Entities", "Use Cases (Services)", "Interfaces for IO", "Dependency Injection"],
            codingTasks: "Refactor the 'Users' API. Handlers parse, Services contain core logic (e.g., check if email exists), Repos save to memory int.",
            miniChallenges: "Ensure the Service layer imports ZERO 'net/http' or DB specific packages.",
            realWorldScenarios: "The company wants to add a gRPC interface alongside REST. Because your logic is in Handlers, it's impossible. Refactor.",
            deliverables: "Complete architectural restructure of the project.",
            githubExpectations: "Massive refactor PR with a clear diagram in the PR description.",
            documentationTasks: "Write `ARCHITECTURE.md` explaining the flow of control.",
            testingRequirements: "Unit test the Service layer fully by injecting a mock Repository."
          },
           {
            day: 5,
            title: "Graceful Shutdown & App Config",
            goal: "Ensure zero-downtime deployments and 12-factor compliance.",
            technologies: ["os/signal", "viper or envconfig"],
            concepts: ["SIGTERM/SIGINT", "12-Factor App", "Connection draining"],
            codingTasks: "Implement an environment variable loader. Catch SIGTERM and give the `http.Server` 10 seconds to finish active requests.",
            miniChallenges: "Simulate a long-running 8-second request, trigger SIGTERM, and watch it finish before the app exits.",
            realWorldScenarios: "During Kubernetes rolling updates, active payments are being dropped. Graceful shutdown halts new traffic but finishes current.",
            deliverables: "Production-ready `main.go` bootstrap sequence.",
            githubExpectations: "Commit configuring safe signals and environment variables.",
            documentationTasks: "Add `.env.example` mapping all required configurations.",
            testingRequirements: "Integration test confirming environment variable overrides."
          }
        ]
      },
      {
        week: 2,
        theme: "PostgreSQL & Database Design",
        whyItMatters: "Data outlives code. A poor schema will cripple your application as it scales. Go must interact with the DB efficiently and safely.",
        juniorMistakes: "Concatenating SQL strings (SQL injection). Fetching all columns `SELECT *`. Not using transactions for multi-step writes.",
        midLevelMindset: "Understand exactly what indexes are being hit. Manage connection pools carefully.",
        days: [
          {
            day: 1,
            title: "Schema Design & Migrations",
            goal: "Define the relational model and automate schema changes.",
            technologies: ["PostgreSQL", "golang-migrate/migrate"],
            concepts: ["Normal forms", "Foreign keys", "Up/Down migrations", "UUID vs Serial"],
            codingTasks: "Design a schema for 'Users', 'Clusters', and 'Deployments'. Write up and down SQL migration files and apply them via CLI.",
            miniChallenges: "Add a composite unique constraint so a user cannot create two clusters with the exact same name.",
            realWorldScenarios: "You need to add a 'status' column to a production table of 10 million rows without locking it.",
            deliverables: "A folder of `.sql` migration files and an ERD diagram.",
            githubExpectations: "PR with the initial schema definition and tooling setup.",
            documentationTasks: "Document how to spin up a local DB and run migrations for a new developer.",
            testingRequirements: "Empty."
          },
          {
            day: 2,
            title: "Database/SQL & Connection Pooling",
            goal: "Connect Go to Postgres robustly.",
            technologies: ["database/sql", "lib/pq or pgx"],
            concepts: ["Connection pool sizing", "Ping", "Prepared statements"],
            codingTasks: "Initialize the database connection. Configure `MaxOpenConns`, `MaxIdleConns`, and `ConnMaxLifetime` based on best practices.",
            miniChallenges: "Write a health check endpoint `/api/health` that pings the database to ensure it's alive.",
            realWorldScenarios: "Spiky traffic exhausts database connections, causing 'too many clients' errors.",
            deliverables: "A centralized database connection manager.",
            githubExpectations: "Commit setting strict pooling parameters.",
            documentationTasks: "Comment the reasoning behind the chosen pool size numbers.",
            testingRequirements: "Write tests asserting the DB returns an error if a bad connection string is passed."
          },
          {
            day: 3,
            title: "Safe Querying & Scanning",
            goal: "Execute queries and map rows to Go structs safely.",
            technologies: ["sqlx or scany"],
            concepts: ["SQL Injection prevention", "Row scanning", "Null types"],
            codingTasks: "Implement the Repository interface methods (CreateDeployment, GetDeployment) using raw SQL mapped into structs.",
            miniChallenges: "Handle a nullable database column using `sql.NullString` or a pointer.",
            realWorldScenarios: "A user named `Robert'; DROP TABLE Students;--` registers. Ensure parametrized queries prevent the injection.",
            deliverables: "A fully functional Postgres repository implementation.",
            githubExpectations: "PR swapping the Memory Repository from Week 1 with the Postgres Repository.",
            documentationTasks: "Document which fields in the structs cover nullable columns.",
            testingRequirements: "Write integration tests that assert data is inserted and retrieved exactly."
          },
          {
            day: 4,
            title: "Transactions & ACID",
            goal: "Ensure data consistency across multiple writes.",
            technologies: ["sql.Tx", "Rollbacks"],
            concepts: ["Atomicity", "Isolation levels", "Deadlocks"],
            codingTasks: "Write a 'DecommissionCluster' service method that updates the cluster status AND marks all associated deployments as terminated within a single transaction.",
            miniChallenges: "Ensure `defer tx.Rollback()` is used safely to catch panics.",
            realWorldScenarios: "A user tries to transfer money. The debit succeeds but the credit fails, destroying money.",
            deliverables: "Service layer executing complex multi-table operations atomically.",
            githubExpectations: "Commit refactoring multi-stage writes to use transaction blocks.",
            documentationTasks: "Document the transactional boundaries of the application.",
            testingRequirements: "Write a test that intentionally errors halfway through a transaction and asserts the DB state is unchanged."
          },
          {
            day: 5,
            title: "Indexes & Query Optimization",
            goal: "Ensure queries scale gracefully as tables grow.",
            technologies: ["EXPLAIN ANALYZE"],
            concepts: ["B-Tree Indexes", "Sequential Scans", "N+1 Problem"],
            codingTasks: "Seed the database with 100,000 dummy deployments. Run a query filtering by `user_id`. Add an index to `user_id` and compare execution times.",
            miniChallenges: "Fix an N+1 query in a hypothetical 'ListClustersWithDeployments' endpoint by using a SQL JOIN.",
            realWorldScenarios: "An endpoint takes 3 seconds to load for power users. EXPLAIN ANALYZE reveals a slow sequential scan.",
            deliverables: "A new migration file adding performance indexes.",
            githubExpectations: "PR explicitly comparing query costs before and after the new index.",
            documentationTasks: "Include the EXPLAIN ANALYZE outputs in the PR description.",
            testingRequirements: "Add tests enforcing an upper limit on query execution time."
          }
        ]
      }
    ]
  },
  {
    month: 3,
    title: "Scaling Up: Microservices, gRPC & Redis",
    focus: "Communicating across multiple services, caching state, and defining strict API contracts.",
    capstoneProject: "A URL Shortener with a Go/REST frontend router and a Go/gRPC backend generator, utilizing Redis caching.",
    architectureReview: "Monolith vs Microservices tradeoffs. When NOT to use microservices.",
    performanceReview: "Redis hit/miss ratios. Analyzing protobuf serialization performance vs JSON.",
    productionChecklist: [
      "gRPC deadlines and timeouts configured.",
      "Redis connection pool configured correctly.",
      "Distributed tracing (OpenTelemetry) context passed between services.",
      "Cache stampede prevention implemented."
    ],
    weeks: [
       {
        week: 1,
        theme: "gRPC and Protobuf",
        whyItMatters: "Internal service-to-service JSON is slow and loosely typed. gRPC enforces contracts and binary speed.",
        juniorMistakes: "Treating gRPC like REST. Not handling backward compatibility in proto files. Forgetting context timeouts.",
        midLevelMindset: "Design schemas for forward-compatibility. Assume network calls will fail.",
        days: [
          {
            day: 1,
            title: "Protobuf Schema Design",
            goal: "Define the strict API contract using Protocol Buffers.",
            technologies: ["Protobuf (v3)", "protoc", "protoc-gen-go", "protoc-gen-go-grpc"],
            concepts: ["Message types", "Service definitions", "Field numbers", "Backward compatibility"],
            codingTasks: "Write a `.proto` file for the URL Shortener backend generator. Define a `GenerateShortUrlRequest` and `GenerateShortUrlResponse`.",
            miniChallenges: "Add validation rules to the proto file using `protoc-gen-validate`.",
            realWorldScenarios: "A client needs to send a custom expiration date for a short URL. You must add this field without breaking older clients.",
            deliverables: "Compiled `*.pb.go` and `*_grpc.pb.go` files injected into the project.",
            githubExpectations: "Commit with the `.proto` file and a generated Makefile step for building them.",
            documentationTasks: "Document the field numbering strategy for future updates.",
            testingRequirements: "Write unit tests to verify protobuf serialization/deserialization.",
          },
          {
            day: 2,
            title: "Building the gRPC Server",
            goal: "Implement the backend generator logic satisfying the gRPC interface.",
            technologies: ["google.golang.org/grpc"],
            concepts: ["UnimplementedServer embedding", "Listen and Serve", "Dependency Injection in gRPC handlers"],
            codingTasks: "Create the server struct, embed `UnimplementedUrlShortenerServer`, and implement the `GenerateShortUrl` RPC. Connect it to a dummy memory store.",
            miniChallenges: "Implement a unique hash generator (e.g., base62) for the short URL logic within the handler.",
            realWorldScenarios: "Your server is starting up but failing to bind to a port because it's already in use. Ensure graceful startup and port configuration via env.",
            deliverables: "A runnable gRPC server listening on a specific port.",
            githubExpectations: "PR titled 'Feature: URL Generator gRPC Server Core'.",
            documentationTasks: "Write an overview of how the base62 algorithm works in the codebase.",
            testingRequirements: "Write service-level unit tests bypassing the network layer by calling the handler directly.",
          },
          {
            day: 3,
            title: "gRPC Client & Context Propagation",
            goal: "Connect the frontend REST API to the background gRPC generator.",
            technologies: ["grpc.Dial", "grpc.WithTransportCredentials"],
            concepts: ["Connection management", "Context deadlines", "Insecure transport (dev) vs TLS (prod)"],
            codingTasks: "Initialize a gRPC client in the REST API project. Call the backend when a user requests a new short URL. Pass the HTTP context to the gRPC client.",
            miniChallenges: "Set a strict 200ms context timeout on the gRPC call.",
            realWorldScenarios: "The backend generator service goes down. Your REST API hangs indefinitely. Add deadlines to fail fast.",
            deliverables: "REST API successfully proxying logic to the gRPC backend.",
            githubExpectations: "Commit integrating the gRPC client into the REST API's dependency injection container.",
            documentationTasks: "Document the expected latency between the REST and gRPC service.",
            testingRequirements: "Mock the gRPC client interface to test the REST handler's timeout handling.",
          },
          {
            day: 4,
            title: "Interceptors & Observability",
            goal: "Add middleware to gRPC for cross-cutting concerns.",
            technologies: ["grpc.UnaryInterceptor", "grpc_middleware (library)"],
            concepts: ["Unary vs Stream interceptors", "Logging interceptors", "Recovery interceptors"],
            codingTasks: "Write a logging interceptor that records request duration, method name, and status code. Add a panic recovery interceptor.",
            miniChallenges: "Extract a Correlation ID from the incoming gRPC metadata and add it to the Go context for structured logging.",
            realWorldScenarios: "A bug in the base62 generator causes a panic. The recovery interceptor must catch it and return an INTERNAL status code.",
            deliverables: "gRPC server with chained logging and recovery interceptors.",
            githubExpectations: "PR adding standard observability interceptors to the server.",
            documentationTasks: "Document how metadata is passed from REST -> gRPC.",
            testingRequirements: "Write tests that intentionally panic the handler to ensure the interceptor recovers.",
          },
          {
            day: 5,
            title: "Error Handling & Status Codes",
            goal: "Return rich, standardized errors over gRPC.",
            technologies: ["google.golang.org/grpc/status", "google.golang.org/grpc/codes"],
            concepts: ["gRPC Status Codes", "Rich error details (google/rpc/status.proto)"],
            codingTasks: "Map domain errors (e.g., 'URL already exists', 'Invalid input') to standard gRPC codes (ALREADY_EXISTS, INVALID_ARGUMENT).",
            miniChallenges: "Attach a custom detail payload (e.g., a `BadRequest` proto message) to a status error.",
            realWorldScenarios: "The REST API needs to return a 400 Bad Request with field-level errors when the gRPC backend rejects the input. Map gRPC statuses back to HTTP codes.",
            deliverables: "A robust error mapping layer between gRPC and the REST frontend.",
            githubExpectations: "Commit replacing raw `errors.New` with `status.Errorf` in the gRPC server.",
            documentationTasks: "Write a mapping table of domain errors -> gRPC codes -> HTTP codes.",
            testingRequirements: "Assert that the client correctly receives and unpacks the rich status errors.",
          }
        ]
       },
       {
        week: 2,
        theme: "Caching & Distributed State with Redis",
        whyItMatters: "Databases are too slow for high-throughput reads. Caching is mandatory at scale, but introduces cache invalidation challenges.",
        juniorMistakes: "Caching everything endlessly. Not handling cache misses cleanly. Creating a thundering herd (cache stampede).",
        midLevelMindset: "Understand TTLs, eviction policies, and cache coherence. Default to failing open.",
        days: [
          {
            day: 1,
            title: "Redis Basics & Connection Management",
            goal: "Integrate Redis safely into a Go application.",
            technologies: ["Redis", "go-redis/redis"],
            concepts: ["Connection pools", "Key-value stores", "Data types (Strings, Hashes)"],
            codingTasks: "Initialize a `go-redis` client. Write a wrapper service that can `Set` and `Get` basic strings.",
            miniChallenges: "Configure the Redis client to timeout connecting after 2 seconds to prevent locking the app on boot.",
            realWorldScenarios: "Your cache is offline. If your app crashes because it can't connect, you have a hard dependency. It should just fall back to DB.",
            deliverables: "A connected Redis client with graceful degration functionality.",
            githubExpectations: "PR introducing Redis to the `docker-compose.yml` and the Go backend.",
            documentationTasks: "Document the required ENV variables for Redis connections.",
            testingRequirements: "Write integration tests that use a tool like 'miniredis' bound to localhost.",
          },
          {
            day: 2,
            title: "Read-Through Caching Pattern",
            goal: "Accelerate read-heavy API endpoints.",
            technologies: ["JSON serialization"],
            concepts: ["Cache miss", "Cache hit", "TTL (Time to Live)"],
            codingTasks: "Implement caching for URL redirection. Check Redis first. On miss, fetch from DB, save to Redis with a 1-hour TTL, and return.",
            miniChallenges: "Serialize a Go struct to JSON before storing it in Redis, and deserialize it on fetch.",
            realWorldScenarios: "A viral marketing link is being clicked 10,000 times a second. Caching prevents your Postgres DB from melting.",
            deliverables: "A lightning-fast redirect endpoint hitting Redis directly.",
            githubExpectations: "Commit wrapping the repository layer with a caching proxy pattern.",
            documentationTasks: "Specify the naming convention for cache keys (e.g., `url:{short_id}`).",
            testingRequirements: "Unit test a cache miss scenario ensuring the DB is called specifically once per miss.",
          },
          {
            day: 3,
            title: "Cache Invalidation & Mutating Data",
            goal: "Keep the cache in sync with the source of truth.",
            technologies: ["Redis DEL"],
            concepts: ["Cache invalidation", "Stale data", "Race conditions in caching"],
            codingTasks: "When a URL's destination is updated via the API, actively delete the corresponding key in Redis.",
            miniChallenges: "Implement a 'soft delete' that removes the key from Redis immediately but leaves it in the DB.",
            realWorldScenarios: "Phil Karlton said 'There are only two hard things in Computer Science: cache invalidation and naming things.' Handle stale reads safely.",
            deliverables: "Consistent API updates that never return stale data.",
            githubExpectations: "PR adding invalidation logic to all mutating endpoints.",
            documentationTasks: "Diagram the flow of a write request updating both DB and Cache.",
            testingRequirements: "Write a test that writes, changes, and reads, asserting the new data is fetched.",
          },
          {
            day: 4,
            title: "Rate Limiting with Redis",
            goal: "Protect the API from abuse using distributed memory.",
            technologies: ["Redis INCR", "EXPIRE"],
            concepts: ["Token Bucket", "Fixed Window Counters"],
            codingTasks: "Build a global rate limiter middleware. Allow users 100 requests per minute per IP using a Fixed Window counter in Redis.",
            miniChallenges: "Return an HTTP 429 status code and a `Retry-After` header when limited.",
            realWorldScenarios: "A malicious user is trying to brute force short URLs. Rate limit their IP specifically.",
            deliverables: "A reusable rate-limit middleware.",
            githubExpectations: "Commit implementing `INCR` and `EXPIRE` atomically.",
            documentationTasks: "Document how to bypass the rate limiter for internal service accounts.",
            testingRequirements: "Spam the endpoint in a test loop and assert it eventually returns 429.",
          },
          {
            day: 5,
            title: "Preventing Cache Stampedes",
            goal: "Ensure high-concurrency systems don't collapse on TTL expiration.",
            technologies: ["golang.org/x/sync/singleflight"],
            concepts: ["Thundering Herd", "Singleflight pattern", "Locking"],
            codingTasks: "Wrap the DB-fetching logic on a cache miss with `singleflight.Group`. Ensure that if 1000 requests miss simultaneously, the DB is hit EXACTLY once.",
            miniChallenges: "Use `singleflight.DoChan` with a context timeout so waiting requests don't hang forever.",
            realWorldScenarios: "A popular cached item expires. Instantly, 5,000 requests hit the DB trying to rebuild it, crashing the DB.",
            deliverables: "Bulletproof cache miss logic.",
            githubExpectations: "PR introducing Singleflight and a demonstration of its effectiveness.",
            documentationTasks: "Write comments explaining exactly how singleflight deduplicates identical concurrent calls.",
            testingRequirements: "Spawn 100 concurrent goroutines triggering a cache miss; assert the DB fetch mock is called exactly 1 time.",
          }
        ]
       }
    ]
  },
   {
    month: 4,
    title: "DevOps, Platform & Observability",
    focus: "Taking code from localhost to a resilient, observable production environment.",
    capstoneProject: "Fully automated CI/CD pipeline deploying the API to a local Kubernetes cluster (Minikube/Kind) with Prometheus/Grafana.",
    architectureReview: "Infrastructure as Code. Defining resilient deployment strategies.",
    performanceReview: "Load testing cluster using k6. Analyzing Grafana dashboards for bottleneck identification.",
    productionChecklist: [
      "Liveness and Readiness probes configured.",
      "Prometheus metrics exposed (`/metrics`).",
      "Docker image size < 50MB (using multi-stage builds and Alpine/Scratch).",
      "Secrets injected securely, not hardcoded."
    ],
    weeks: [
      {
        week: 1,
        theme: "Containerization with Docker",
        whyItMatters: "Applications must run consistently across all environments. Docker solves the 'it works on my machine' problem.",
        juniorMistakes: "Running processes as root. Creating massive 1GB images for a 10MB Go binary. Embedding secrets in images.",
        midLevelMindset: "Images should be minimal, immutable, and secure. Use multi-stage builds and distroless/scratch bases.",
        days: [
          {
            day: 1,
            title: "Docker Fundamentals & Multi-Stage Builds",
            goal: "Package a Go application into an ultra-small, secure container.",
            technologies: ["Docker", "Alpine Linux", "Scratch"],
            concepts: ["Layers", "Multi-stage builds", "CGO_ENABLED=0", "Image sizing"],
            codingTasks: "Write a Dockerfile for the URL Shortener API. Use golang:alpine for the builder stage, and 'scratch' for the final runtime stage.",
            miniChallenges: "Mount a volume to cache go modules during the build process to speed up subsequent builds.",
            realWorldScenarios: "Your company's cloud costs are high because deployments take 10 minutes to pull 2GB images. Reduce the image size under 20MB.",
            deliverables: "A production-optimized Dockerfile.",
            githubExpectations: "PR adding standard Dockerfile and `.dockerignore`.",
            documentationTasks: "Document the commands to build and run the image locally.",
            testingRequirements: "Use `container-structure-test` or manual run to verify the compiled binary executes correctly.",
          },
          {
            day: 2,
            title: "Docker Compose & Local Environments",
            goal: "Mirror the production stack on localhost for seamless development.",
            technologies: ["Docker Compose", "YAML"],
            concepts: ["Services", "Networks", "Volumes", "Depends_on"],
            codingTasks: "Create a `docker-compose.yml` that boots the Go API, Postgres DB, and Redis cache simultaneously. Seed the database on startup.",
            miniChallenges: "Configure healthchecks in compose so the Go API waits until Postgres is ready before starting.",
            realWorldScenarios: "New devs take 3 days to install databases and dependencies. You need them committing code in 3 hours.",
            deliverables: "A one-click `docker-compose up -d` development environment.",
            githubExpectations: "Commit introducing compose file and initialization scripts.",
            documentationTasks: "Update the README with the new onboarding instructions.",
            testingRequirements: "Verify data persistence by bringing the stack down and up, checking if DB data survives.",
          },
          {
            day: 3,
            title: "Observability: Structured Logging",
            goal: "Make application behavior searchable and quantifiable.",
            technologies: ["log/slog", "JSON"],
            concepts: ["Structured vs Unstructured logs", "Log levels", "Contextual logging"],
            codingTasks: "Replace standard `log.Print` throughout the app with Go 1.21+ `slog`. Output JSON format to stdout.",
            miniChallenges: "Write a middleware that automatically attaches the HTTP method, path, and duration to every `slog` entry.",
            realWorldScenarios: "A user reports a failed payment, but the logs just say 'payment failed' with no User ID. Add context.",
            deliverables: "A globally configured structured logger injected into services.",
            githubExpectations: "PR swapping the logging engine across all files.",
            documentationTasks: "Document standard keys that should always be logged (e.g., `user_id`, `trace_id`).",
            testingRequirements: "Write unit tests simulating log output and parsing the resulting JSON.",
          },
          {
            day: 4,
            title: "Metrics with Prometheus",
            goal: "Expose application health and performance metrics to scrapers.",
            technologies: ["Prometheus Go Client", "HTTP /metrics"],
            concepts: ["Counters", "Gauges", "Histograms", "Pull-based monitoring"],
            codingTasks: "Add a `/metrics` endpoint to the REST API. Track total HTTP requests (Counter) and request latency (Histogram).",
            miniChallenges: "Track the number of active database connections continuously using a Gauge.",
            realWorldScenarios: "You suspect the API is slowing down during peak hours but have no proof. Histograms provide percentile latencies (p95, p99).",
            deliverables: "An API that successfully exposes standard Prometheus metrics.",
            githubExpectations: "Commit adding metrics middleware and registering collectors.",
            documentationTasks: "Comment the bucket sizes chosen for the latency histogram (e.g., [10ms, 50ms, 100ms]).",
            testingRequirements: "Hit the `/metrics` endpoint in a test and assert the counter string format is correct.",
          },
          {
            day: 5,
            title: "CI/CD & GitHub Actions",
            goal: "Automate testing, linting, and building on every push.",
            technologies: ["GitHub Actions", "YAML"],
            concepts: ["Workflows", "Jobs", "Steps", "Secrets management", "Matrix builds"],
            codingTasks: "Create a GitHub Actions workflow that runs `golangci-lint`, runs `go test`, builds the Docker image, and pushes it to Docker Hub or GHCR.",
            miniChallenges: "Use an action to post the test coverage percentage as a comment on the PR.",
            realWorldScenarios: "Devs keep merging code that breaks the build or fails tests. Enforce passing CI for all merges.",
            deliverables: "A green checkmark on GitHub PRs proving the build succeeds.",
            githubExpectations: "PR containing `.github/workflows/ci.yml`.",
            documentationTasks: "Document the required GitHub Secrets for the pipeline to function.",
            testingRequirements: "Ensure the CI properly fails if a test intentionally panics.",
          }
        ]
      },
      {
        week: 2,
        theme: "Kubernetes & Orchestration",
        whyItMatters: "Modern backends are deployed on Kubernetes. You don't need to be an admin, but you must know how your app runs and scales in a cluster.",
        juniorMistakes: "Not setting CPU/Memory limits. Assuming pods have local persistent storage. Hardcoding config values.",
        midLevelMindset: "Design stateless applications. Understand pod lifecycles, configmaps, and secrets.",
        days: [
          {
            day: 1,
            title: "Manifests: Pods & Deployments",
            goal: "Deploy your Dockerized Go API to a local Kubernetes cluster.",
            technologies: ["Minikube/Kind", "kubectl", "YAML"],
            concepts: ["Pods", "Deployments", "ReplicaSets", "Labels and Selectors"],
            codingTasks: "Write a `deployment.yaml` for the URL Shortener API to run 3 replicas. Apply it to a local Minikube or Kind cluster.",
            miniChallenges: "Update the deployment to a new image tag and watch the rolling update in action.",
            realWorldScenarios: "A node goes down in production. Kubernetes automatically schedules a new pod for your deployment on a healthy node.",
            deliverables: "A running multi-replica deployment.",
            githubExpectations: "Commit adding a `/k8s/base` directory with initial manifests.",
            documentationTasks: "Document the `kubectl` commands to inspect logs across multiple pods.",
            testingRequirements: "Manually verify `kubectl get pods` shows 3 running instances.",
          },
          {
            day: 2,
            title: "Services & Ingress",
            goal: "Expose your application to the outside world.",
            technologies: ["Kubernetes Services", "Ingress Controllers"],
            concepts: ["ClusterIP", "NodePort", "LoadBalancer", "Routing"],
            codingTasks: "Write a `service.yaml` to load balance traffic across your 3 pods. Set up a basic Ingress rule mapping a local hostname to your service.",
            miniChallenges: "Configure the Ingress to route `/api/v1` to the REST API and `/grpc` to the gRPC backend.",
            realWorldScenarios: "Clients cannot access your pods directly. The Ingress provides a single entrypoint and handles SSL termination.",
            deliverables: "A fully routed local cluster.",
            githubExpectations: "PR introducing Service and Ingress manifests.",
            documentationTasks: "Document how to update `/etc/hosts` to test the local Ingress.",
            testingRequirements: "Use `curl` to successfully hit the API via the Ingress hostname.",
          },
          {
            day: 3,
            title: "ConfigMaps & Secrets",
            goal: "Inject environment variables without hardcoding them in images.",
            technologies: ["ConfigMap", "Secret"],
            concepts: ["Environment variable injection", "Volume mounts", "Base64 encoding"],
            codingTasks: "Extract the Postgres connection string and Redis host into a Secret and a ConfigMap. Update the Deployment to inject them into the Go pod.",
            miniChallenges: "Mount a ConfigMap as a file inside the pod instead of an environment variable.",
            realWorldScenarios: "Your database password changed. Instead of rebuilding the Docker image, you just update the Secret and restart the pods.",
            deliverables: "A 12-factor compliant Kubernetes deployment.",
            githubExpectations: "Commit separating config from the deployment manifest.",
            documentationTasks: "Add warnings about Secret Base64 encoding NOT being encryption.",
            testingRequirements: "Describe the pod and verify the environment variables are sourced from the ConfigMap.",
          },
          {
            day: 4,
            title: "Probes & Self-Healing",
            goal: "Tell Kubernetes when your app is ready to receive traffic, and when it needs a restart.",
            technologies: ["Liveness Probe", "Readiness Probe"],
            concepts: ["HTTP GET probes", "Initial delay", "Failure thresholds"],
            codingTasks: "Implement `/health/liveness` and `/health/readiness` endpoints in Go. Add the probes to your `deployment.yaml`.",
            miniChallenges: "Make the readiness probe fail if the database connection drops, but keep liveness passing.",
            realWorldScenarios: "The Go API starts, but takes 5 seconds to connect to Postgres. Kubernetes routes traffic immediately, causing 500s. Readiness probes prevent this.",
            deliverables: "A self-healing, zero-downtime deployment.",
            githubExpectations: "PR implementing detailed health endpoints and K8s probes.",
            documentationTasks: "Differentiate liveness (should I restart the pod?) vs readiness (should I send traffic here?) in the README.",
            testingRequirements: "Simulate a DB outage and watch Kubernetes automatically remove the pod from the Service endpoints.",
          },
          {
            day: 5,
            title: "Resource Limits & HPA",
            goal: "Prevent your app from consuming the whole cluster, and auto-scale on demand.",
            technologies: ["Horizontal Pod Autoscaler (HPA)", "Metrics Server"],
            concepts: ["Requests vs Limits", "CPU Throttling", "OOMKilled"],
            codingTasks: "Set CPU/Memory requests and limits on the pod. Create an HPA resource to scale replicas up to 10 if CPU usage exceeds 70%.",
            miniChallenges: "Use a load testing tool to artificially spike CPU usage and watch the HPA scale up.",
            realWorldScenarios: "Black Friday traffic hits. Instead of waking up at 3 AM to manually add servers, HPA scales your pods automatically.",
            deliverables: "An autoscaling cluster configuration.",
            githubExpectations: "Commit defining exact resource boundaries and scaling policies.",
            documentationTasks: "Document the expected memory footprint of the Go binary under normal load.",
            testingRequirements: "Produce an OOMKilled error intentionally by setting the memory limit artificially low, then fix it.",
          }
        ]
      }
    ]
  },
   {
    month: 5,
    title: "System Design, Event-Driven & Career",
    focus: "Asynchronous processing, message brokers, system design interviews, and job prep.",
    capstoneProject: "Event-driven notification system using RabbitMQ/Kafka to process background emails and webhooks.",
    architectureReview: "Choreography vs Orchestration in event-driven systems. Dealing with duplicate events.",
    performanceReview: "Message broker throughput and latency. Tuning consumer worker counts.",
    productionChecklist: [
      "Idempotent consumer logic.",
      "Dead Letter Queues (DLQ) configured for failed messages.",
      "Retry mechanisms with exponential backoff.",
      "Comprehensive system diagrams ready for interviews."
    ],
    weeks: [
      {
        week: 1,
        theme: "System Design & Event-Driven Architecture",
        whyItMatters: "At enterprise scale, synchronous HTTP APIs bottleneck. Event brokers allow decoupled, resilient scaling.",
        juniorMistakes: "Using synchronous calls for everything. Processing long jobs in HTTP handlers. Not handling duplicate messages.",
        midLevelMindset: "Expect failure. Embrace eventual consistency and idempotency in consumers.",
        days: [
          {
            day: 1,
            title: "Message Brokers & Asynchronous Jobs",
            goal: "Understand pub/sub and queue architectures.",
            technologies: ["RabbitMQ or Kafka", "AMQP"],
            concepts: ["Exchanges", "Queues", "Topics", "Consumer Groups"],
            codingTasks: "Set up RabbitMQ in docker-compose. Write a simple Go script that publishes 'UserRegistered' events to a topic.",
            miniChallenges: "Implement a fan-out exchange where one message triggers two different queues.",
            realWorldScenarios: "When a user signs up, you need to send an email, create a billing record, and notify Slack. Do not do this synchronously in the REST handler.",
            deliverables: "A generic Publisher package wrapping the AMQP dialer.",
            githubExpectations: "Commit introducing the messaging layer to the project infrastructure.",
            documentationTasks: "Map out the topic/routing key naming conventions.",
            testingRequirements: "Write tests utilizing a mock publisher interface.",
          },
          {
            day: 2,
            title: "Building Resilient Consumers",
            goal: "Act on asynchronous events safely.",
            technologies: ["Go channels", "AMQP delivery"],
            concepts: ["Acks/Nacks", "Prefetch counts", "Worker scaling"],
            codingTasks: "Write a worker service that listens to the 'email_queue'. When 'UserRegistered' arrives, simulate sending an email, then ACK the message.",
            miniChallenges: "Configure the channel prefetch count to 5 to prevent OOMing the worker with 10k sudden messages.",
            realWorldScenarios: "If the email API is down, the worker panics and the message is lost forever. Implement graceful NACKing.",
            deliverables: "A scalable, independent worker binary consuming messages.",
            githubExpectations: "PR adding the new worker executable alongside the main API.",
            documentationTasks: "Explain how to horizontally scale this worker using Kubernetes.",
            testingRequirements: "Simulate a consumer processing delay and ensure the message remains unacked during process.",
          },
          {
            day: 3,
            title: "Idempotency & Dead Letter Queues",
            goal: "Handle duplicates and permanent failures professionally.",
            technologies: ["Postgres (for idempotency keys)", "RabbitMQ DLX"],
            concepts: ["Idempotency keys", "Dead letters", "Exponential backoff"],
            codingTasks: "Update the consumer: check if `event_id` exists in the DB before processing. Configure a Dead Letter Exchange for messages that fail 3 times.",
            miniChallenges: "Implement exponential backoff so retries happen at 1s, 2s, 4s, etc.",
            realWorldScenarios: "A network blip causes RabbitMQ to send the same 'ProcessPayment' event twice. Only charge the customer once.",
            deliverables: "Idempotent consumer logic resistant to at-least-once delivery issues.",
            githubExpectations: "Commit focusing strictly on idempotency state tracking.",
            documentationTasks: "Write an incident response playbook: 'How to replay messages from the DLQ'.",
            testingRequirements: "Send the exact same event payload twice, assert the logic fires only once.",
          },
          {
            day: 4,
            title: "System Design Prep: The Whiteboard",
            goal: "Translate architecture skills into interview performance.",
            technologies: ["Excalidraw", "Draw.io"],
            concepts: ["Load balancers", "Caching layers", "Database sharding", "CAP theorem basics"],
            codingTasks: "No coding. Draw a complete diagram of a global News Feed architecture. Detail CDN, API Gateway, Cache, Read/Write DBs.",
            miniChallenges: "Calculate rough estimations (QPS, Storage, Bandwidth) for 1 Million Daily Active Users.",
            realWorldScenarios: "Interview Question: 'Design Twitter'. Focus on the fan-out service for celebrity users vs standard users.",
            deliverables: "A PDF architecture blueprint.",
            githubExpectations: "PR merging the blueprint into an `architecture/` folder.",
            documentationTasks: "Write a 1-page summary explaining the tradeoffs chosen (Consistency vs Availability).",
            testingRequirements: "Peer review: defend your design against a senior engineer's critique.",
          },
          {
            day: 5,
            title: "The Mid-Level Interview & Portfolio Polish",
            goal: "Finalize the portfolio and pass the technical screens.",
            technologies: ["Go Toolchain", "Leetcode"],
            concepts: ["Concurrency debugging", "Live coding", "Resume tuning"],
            codingTasks: "Review the entire codebase. Ensure golangci-lint passes with zero warnings. Complete 3 medium Leetcode problems using Go.",
            miniChallenges: "Solve a Leetcode problem strictly using Go's `container/heap` package.",
            realWorldScenarios: "Live debugging interview: The interviewer gives you a codebase with a subtle Goroutine leak. Find and fix it using pprof.",
            deliverables: "A stellar, interview-ready GitHub profile and polished capstone projects.",
            githubExpectations: "Final cleanup commits: removing dead code, fixing typos, expanding READMEs.",
            documentationTasks: "Write a conclusive 'Lessons Learned' blog post or markdown file.",
            testingRequirements: "Ensure 100% of pipeline tests across all microservices are green.",
          }
        ]
      },
      {
        week: 2,
        theme: "Security, Hardening & Soft Skills",
        whyItMatters: "Building features gets you hired; securing them and leading teams gets you promoted to Senior.",
        juniorMistakes: "Storing plaintext passwords. Ignoring OWASP Top 10. Thinking purely technically without considering business value.",
        midLevelMindset: "Security is non-negotiable. Communicate technical tradeoffs to product owners securely and clearly.",
        days: [
          {
            day: 1,
            title: "Authentication & Cryptography in Go",
            goal: "Securely store and verify user credentials.",
            technologies: ["golang.org/x/crypto/bcrypt"],
            concepts: ["Hashing vs Encryption", "Salts", "Rainbow Tables", "Constant-time comparisons"],
            codingTasks: "Implement password registration using bcrypt. Use a cost of at least 12.",
            miniChallenges: "Add a password strength validator (min 8 chars, 1 uppercase, 1 special).",
            realWorldScenarios: "A database node is stolen. Because you used bcrypt with a high work factor, the passwords remain computationally impossible to crack.",
            deliverables: "A secure authentication registration endpoint.",
            githubExpectations: "PR adding bcrypt and removing any plaintext password traces.",
            documentationTasks: "Document the bcrypt cost factor chosen and why.",
            testingRequirements: "Write tests proving that the exact same password hashes to a different string each time.",
          },
          {
            day: 2,
            title: "Stateless Auth with JWT",
            goal: "Authenticate API requests without hitting the database every time.",
            technologies: ["github.com/golang-jwt/jwt"],
            concepts: ["Claims", "Signatures", "HS256 vs RS256", "Token Expiration"],
            codingTasks: "Implement login generating a JWT. Build an authentication middleware that validates the JWT signature on protected routes.",
            miniChallenges: "Inject the authenticated User ID from the JWT claims into the request context.",
            realWorldScenarios: "Horizontal scaling is easy when authentication limits don't bottleneck on the central DB. JWTs verify mathematically.",
            deliverables: "A robust JWT issuing and verification system.",
            githubExpectations: "Commit demonstrating secure secret management for the JWT signing key.",
            documentationTasks: "Explain how to revoke a JWT (e.g., using a Redis blocklist).",
            testingRequirements: "Test that expired JWTs are strictly rejected with a 401 Unauthorized.",
          },
          {
            day: 3,
            title: "OWASP & API Security",
            goal: "Defend against common web vulnerabilities.",
            technologies: ["HTTPS", "helmet equivalent"],
            concepts: ["CORS", "Rate Limiting", "SQL injection (Review)", "CSRF"],
            codingTasks: "Lock down CORS to specific domains. Ensure secure HTTP headers (HSTS, Content-Type-Options) are set on all responses.",
            miniChallenges: "Implement a middleware simulating CSRF token verification for all non-GET requests.",
            realWorldScenarios: "A malicious site makes authenticated requests on behalf of your users (CSRF). Secure cookies and CORS block this.",
            deliverables: "A hardened API resistant to basic scanning attacks.",
            githubExpectations: "PR applying strict middleware security headers.",
            documentationTasks: "Document the allowed CORS origins for development and production.",
            testingRequirements: "Use `curl` to verify standard security headers are attached to responses.",
          },
          {
            day: 4,
            title: "Refactoring & Tech Debt",
            goal: "Identify and eliminate code smells in your own work.",
            technologies: ["goreportcard", "Codebeat"],
            concepts: ["Cyclomatic complexity", "DRY vs WET", "Tech Debt"],
            codingTasks: "Run a complexity analyzer on your project. Pick the 3 most complex functions and refactor them into smaller, testable units.",
            miniChallenges: "Extract a massive inline struct initialization into a proper builder pattern.",
            realWorldScenarios: "A file has grown to 2000 lines. Nobody wants to touch it because it breaks easily. It's time to carve it up.",
            deliverables: "Cleaner, more maintainable code with reduced cognitive load.",
            githubExpectations: "Refactor commit with before/after complexity scores.",
            documentationTasks: "Write an RFC proposing a new code standard for the team.",
            testingRequirements: "Ensure 100% test pass rate after massive structural refactoring.",
          },
          {
            day: 5,
            title: "The Senior Transition: Communication",
            goal: "Speak business impact, not just tech stacks.",
            technologies: ["Markdown", "RFC format"],
            concepts: ["Mentorship", "Stakeholder management", "Cost vs Benefit"],
            codingTasks: "No coding. Write an engineering proposal/RFC for adding a new message broker to the architecture. Justify the cost and maintenance overhead against the business value.",
            miniChallenges: "Review a junior's hypothetical PR. Provide constructive, empathetic feedback rather than blunt criticism.",
            realWorldScenarios: "You want to rewrite the monolith in microservices. The CEO wants to know why it will take 6 months and what business value it brings.",
            deliverables: "A professionally written Architecture Decision Record (ADR) or RFC.",
            githubExpectations: "PR merging the ADR/RFC into a `docs/` folder.",
            documentationTasks: "Review and organize all repository documentation globally.",
            testingRequirements: "Empty.",
          }
        ]
      }
    ]
  }
];

export const finalOutcomes = {
  skillLevel: "Strong Mid-Level Backend Engineer",
  jobTypes: [
    "Backend Software Engineer (Golang)",
    "Distributed Systems Engineer",
    "Platform Engineer / SRE (Junior/Mid)",
    "API / Integration Engineer"
  ],
  portfolio: [
    "Resilient Concurrent File/Data Processor (CLI)",
    "DevOps/Platform REST API (Clean Architecture, Postgres)",
    "URL Shortener Microservices (gRPC, Redis)",
    "Event-Driven Notification System (RabbitMQ/Kafka)",
    "Complete CI/CD & Kubernetes Deployment manifest repo"
  ],
  technologiesMastered: [
    "Golang Core & Concurrency", "PostgreSQL & Database Design", 
    "Docker & Kubernetes basics", "gRPC & Protobuf", 
    "Redis Caching", "RESTful API Design", "Testing (Unit/Integration)",
    "GitHub Actions (CI/CD)", "Prometheus & Observability"
  ],
  weakAreasToContinue: [
    "Advanced Network/Protocol internals",
    "Deep Kubernetes administration",
    "Complex Data Engineering pipelines",
    "Frontend integration"
  ],
  nextSteps: "To reach Senior level: focus heavily on system design, cross-team technical leadership, mastering infrastructure (Terraform/AWS), and guiding architecture design RFCs."
};
